# Site settings
title: Kanav Singla
tagline: DevOps Developer, AWS Certified, Git enthusiast

url: "" # the base hostname & protocol for your site

# Used for theme in head.html, cannot be used in Stylus files
color-primary: "#00bcd4"

# contact
author:
  name: Kanav Singla
  url: http://github.com/KanavNY

linkedin_username: kanavsingla
resume: Resume-Kanav.pdf 

# Others
markdown: kramdown

# Exclude Stylus files, nodemodules, and gulpfile
exclude: [node_modules, gulpfile.js, styl, npm-debug.log, Gemfile, Gemfile.lock, LICENSE, README.md, package.json]
